services:
  app:
    container_name: futile-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    # Set environment variables based on the .env file
    env_file:
      - .env
    ports:
      - 4000:3000
    networks:
      - futile_network
    depends_on:
      - db
  db:
    container_name: futile-db
    image: postgres:16-alpine
    env_file:
      - .env.db
    volumes:
      - db-data-dev:/var/lib/postgresql/data
    ports:
      - 4001:5432
    networks:
      - futile_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  futile_network:
    name: futile_network

volumes:
  db-data-dev:
