import sanitize from "sanitize-html"

// generated by chatgpt
// should be good for anything tiptap outputs and little more
export const htmlSanitizationOptions = {
  allowedTags: [
    "b",
    "i",
    "em",
    "strong",
    "u",
    "s",
    "sub",
    "sup",
    "br",
    "span",
    "ul",
    "ol",
    "li",
    "a",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "div",
    "p",
    "img",
    "table",
    "thead",
    "tbody",
    "tfoot",
    "tr",
    "th",
    "td",
    "code",
    "pre",
  ],
  allowedAttributes: {
    "*": ["class", "id", "style"],
    a: ["href", "target"],
    img: ["src", "alt", "width", "height"],
    td: ["colspan", "rowspan"],
    th: ["colspan", "rowspan"],
  },
  allowedStyles: {
    "*": {
      // Allow specific styles; adjust as needed
      color: [
        /^#[0-9a-fA-F]{3,6}$/,
        /^rgb\((\d{1,3},\s?){2}\d{1,3}\)$/,
        /^rgba\((\d{1,3},\s?){3}\d(\.\d+)?\)$/,
      ],
      "text-align": [/^left$/, /^right$/, /^center$/, /^justify$/],
      "font-weight": [/^bold$/, /^normal$/, /^[1-9]00$/],
      "font-size": [/^\d+(px|em|%)$/],
    },
  },
  transformTags: {
    a: sanitize.simpleTransform("a", {
      target: "_blank",
      rel: "noopener noreferrer",
    }),
  },
}
